apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::891377322331:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-10uelaArQ7Ou
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::891377322331:user/ramesh
      username: ramesh    
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 5996ffe6-d70b-45ba-9a91-1c2474a78483